from django.shortcuts import render
from converter.forms import InputAndResult, ConverterForm, FormChoice,\
    PressureForm, TimeForm, VolumeForm, MassForm, FrequencyForm, SpeedForm,\
    SquareForm, LengthForm, EnergyForm
MEASURE_RATIO = {
    ('kilometer', 'kilometer'): 1.0,
    ('kilometer', 'metr'): 1000.0,
    ('kilometer', 'centimeter'): 100000.0,
    ('kilometer', 'millimeter'): pow(10, 6),
    ('kilometer', 'micrometer'): pow(10, 9),
    ('kilometer', 'nanometer'): pow(10, 12),
    ('kilometer', 'mile'): 1/1.609,
    ('kilometer', 'yard'): 1093.61,
    ('kilometer', 'foot'): 3280.84,
    ('kilometer', 'inch'): 39370,
    ('metr', 'kilometer'):1/1000,
    ('metr', 'metr'): 1.0,
    ('metr', 'centimeter'): 100,
    ('metr', 'millimeter'): 1000,
    ('metr', 'micrometer'): pow(10, 6),
    ('metr', 'nanometer'): pow(10, 9),
    ('metr', 'mile'): 1/1609,
    ('metr', 'yard'): 1.094,
    ('metr', 'foot'): 3.28084,
    ('metr', 'inch'): 39.37,
    ('centimeter', 'kilometer'): 1/100000,
    ('centimeter', 'metr'): 1/100,
    ('centimeter', 'centimeter'): 1.0,
    ('centimeter', 'millimeter'): 10.0,
    ('centimeter', 'micrometer'): 10000.0,
    ('centimeter', 'nanometer'): pow(10, 7),
    ('centimeter', 'mile'): 1/160900,
    ('centimeter', 'yard'): 1/91.44,
    ('centimeter', 'foot'): 1/30.48,
    ('centimeter', 'inch'): 1/2.54,
    ('millimeter', 'kilometer'): 1/pow(10, 6),
    ('millimeter', 'metr'): 1/1000.0,
    ('millimeter', 'centimeter'): 1/10,
    ('millimeter', 'millimeter'): 1,
    ('millimeter', 'micrometer'): 1000,
    ('millimeter', 'nanometer'): pow(10, 6),
    ('millimeter', 'mile'): 1/(1.609*pow(10,6)),
    ('millimeter', 'yard'): 1/914.4,
    ('millimeter', 'foot'): 1/304.8,
    ('millimeter', 'inch'): 1/25.4,
    ('micrometer', 'kilometer'): 1/pow(10, 9),
    ('micrometer', 'metr'): 1/pow(10, 6),
    ('micrometer', 'centimeter'): 1/10000,
    ('micrometer', 'millimeter'): 1/1000,
    ('micrometer', 'micrometer'): 1.0,
    ('micrometer', 'nanometer'): 1000,
    ('micrometer', 'mile'): 1/(1609*pow(10, 9)),
    ('micrometer', 'yard'): 1/914400,
    ('micrometer', 'foot'): 1/304800,
    ('micrometer', 'inch'): 1/25400,
    ('nanometer', 'kilometer'):1/pow(10, 12),
    ('nanometer', 'metr'): 1/pow(10, 9),
    ('nanometer', 'centimeter'): 1/pow(10, 7),
    ('nanometer', 'millimeter'): 1/pow(10, 6),
    ('nanometer', 'micrometer'): 1/1000,
    ('nanometer', 'nanometer'): 1.0,
    ('nanometer', 'mile'):1/(pow(10, 12)*1.609),
    ('nanometer', 'yard'):1/(pow(10, 8)*9.144),
    ('nanometer', 'foot'):1/(pow(10, 8)*3.048),
    ('nanometer', 'inch'):1/(pow(10, 8)*3.048),
    ('mile', 'kilometer'):1.609,
    ('mile', 'metr'):1609,
    ('mile', 'centimeter'):160900,
    ('mile', 'millimeter'):1.609e+6,
    ('mile', 'micrometer'):1.609e+9,
    ('mile', 'nanometer'):1.609e+12,
    ('mile', 'mile'):1,
    ('mile', 'yard'):1760,
    ('mile', 'foot'):5280,
    ('mile', 'inch'):63360,
    ('yard', 'kilometer'):1/1094,
    ('yard', 'metr'):1/1.094,
    ('yard', 'centimeter'):91.44,
    ('yard', 'millimeter'):914.4,
    ('yard', 'micrometer'):914400,
    ('yard', 'nanometer'): 9.144e+8,
    ('yard', 'mile'):1/1760,
    ('yard', 'yard'):1,
    ('yard', 'foot'):3,
    ('yard', 'inch'):36,
    ('foot', 'kilometer'):1/3281,
    ('foot', 'metr'):1/3.281,
    ('foot', 'centimeter'): 30.48,
    ('foot', 'millimeter'): 304.8,
    ('foot', 'micrometer'): 304800,
    ('foot', 'nanometer'):3.048e+8,
    ('foot', 'mile'):1/5280,
    ('foot', 'yard'):1/3,
    ('foot', 'foot'):1,
    ('foot', 'inch'):1/12,
    ('inch', 'kilometer'): 1/39370,
    ('inch', 'metr'):1/39.37,
    ('inch', 'centimeter'):2.54,
    ('inch', 'millimeter'):25.4,
    ('inch', 'micrometer'):25400,
    ('inch', 'nanometer'):2.54e+7,
    ('inch', 'mile'):1/63360,
    ('inch', 'yard'):1/36,
    ('inch', 'foot'):1/12,
    ('inch', 'inch'):1,
    ('bar', 'bar'): 1,
    ('bar', 'torr'): 750.1,
    ('bar', 'pound-force'):14.504,
    ('bar', 'pascal'): 100000,
    ('bar', 'atmosphere'):1/1.013,
    ('torr', 'bar'):1/750.1,
    ('torr', 'torr'): 1,
    ('torr', 'pound-force'): 1/51.715,
    ('torr', 'pascal'): 133.3,
    ('torr', 'atmosphere'): 1/760,
    ('pound-force', 'bar'): 1/14.504,
    ('pound-force', 'torr'): 51.715,
    ('pound-force', 'pound-force'):1,
    ('pound-force', 'pascal'): 6895,
    ('pound-force', 'atmosphere'): 1/14.696,
    ('pascal', 'bar'): 1e-5,
    ('pascal', 'torr'): 1/133.3,
    ('pascal', 'pound-force'): 1/6895,
    ('pascal', 'pascal'):1,
    ('pascal', 'atmosphere'):9.8692e-6,
    ('atmosphere', 'bar'):9,
    ('atmosphere', 'torr'):760,
    ('atmosphere', 'pound-force'): 14.696,
    ('atmosphere', 'pascal'):101300,
    ('atmosphere', 'atmosphere'):1,
    ('hertz', 'hertz'):1,
    ('hertz', 'megahertz'):1/1e+6,
    ('hertz', 'kilohertz'):1/1000,
    ('hertz', 'gigahertz'):1/1e+9,
    ('megahertz', 'hertz'):1e+6,
    ('megahertz', 'megahertz'):1,
    ('megahertz', 'kilohertz'):1000,
    ('megahertz', 'gigahertz'):1/1000,
    ('kilohertz', 'hertz'):1000,
    ('kilohertz', 'megahertz'):1/1000,
    ('kilohertz', 'kilohertz'):1,
    ('kilohertz', 'gigahertz'):1/1e+6,
    ('gigahertz', 'hertz'):1e+9,
    ('gigahertz', 'megahertz'):1e+6,
    ('gigahertz', 'kilohertz'):1000,
    ('gigahertz', 'gigahertz'):1,
    ('joule', 'joule'):1,
    ('joule', 'kilojoule'):1/1000,
    ('joule', 'gram-calorie'):1/4.184,
    ('joule', 'kilocalorie'):1/4184,
    ('joule', 'watt-hour'):1/3600,
    ('joule', 'kilowatt-hour'):1/3.6e+6,
    ('kilojoule', 'joule'):1000,
    ('kilojoule', 'kilojoule'):1,
    ('kilojoule', 'gram-calorie'):239,
    ('kilojoule', 'kilocalorie'):1/4.184,
    ('kilojoule', 'watt-hour'):1/3.6,
    ('kilojoule', 'kilowatt-hour'):1/3600,
    ('gram-calorie', 'joule'):4.184,
    ('gram-calorie', 'kilojoule'):1/239,
    ('gram-calorie', 'gram-calorie'):1,
    ('gram-calorie', 'kilocalorie'):1/1000,
    ('gram-calorie', 'watt-hour'):1/860.4,
    ('gram-calorie', 'kilowatt-hour'):1/860400,
    ('kilocalorie', 'joule'):4184,
    ('kilocalorie', 'kilojoule'):4.184,
    ('kilocalorie', 'gram-calorie'):1000,
    ('kilocalorie', 'kilocalorie'):1,
    ('kilocalorie', 'watt-hour'):1.162,
    ('kilocalorie', 'kilowatt-hour'):1/860.4,
    ('watt-hour', 'joule'):3600,
    ('watt-hour', 'kilojoule'):3.6,
    ('watt-hour', 'gram-calorie'):860.4,
    ('watt-hour', 'kilocalorie'):1/1.162,
    ('watt-hour', 'watt-hour'):1,
    ('watt-hour', 'kilowatt-hour'):1/1000,
    ('kilowatt-hour', 'joule'):3.6e+6,
    ('kilowatt-hour', 'kilojoule'):3600,
    ('kilowatt-hour', 'gram-calorie'):860400,
    ('kilowatt-hour', 'kilocalorie'):860.4,
    ('kilowatt-hour', 'watt-hour'):1000,
    ('kilowatt-hour', 'kilowatt-hour'):1,
    ('millisecond', 'millisecond'):1,
    ('millisecond', 'second'):1/1000,
    ('millisecond', 'minute'):1/60000,
    ('millisecond', 'hour'):1/3.6e+6,
    ('millisecond', 'day'):1/8.64e+7,
    ('millisecond', 'week'):1/6.048e+8,
    ('millisecond', 'month'):1/2.628e+9,
    ('millisecond', 'year'):1/3.154e+10,
    ('second', 'millisecond'):1000,
    ('second', 'second'):1,
    ('second', 'minute'):1/60,
    ('second', 'hour'):1/3600,
    ('second', 'day'):1/86400,
    ('second', 'week'):1/604800,
    ('second', 'month'):1/3.154e+10,
    ('second', 'year'):1/3.154e+7,
    ('minute', 'millisecond'):60000,
    ('minute', 'second'):60,
    ('minute', 'minute'):1,
    ('minute', 'hour'):1/60,
    ('minute', 'day'):1/1440,
    ('minute', 'week'):1/10080,
    ('minute', 'month'):2.2831e-5,
    ('minute', 'year'):1.9026e-6,
    ('hour', 'millisecond'):3.6e+6,
    ('hour', 'second'):3600,
    ('hour', 'minute'):60,
    ('hour', 'hour'):1,
    ('hour', 'day'):1/24,
    ('hour', 'week'):1/168,
    ('hour', 'month'):1/730,
    ('hour', 'year'):1/8760,
    ('day', 'millisecond'):8.64e+7,
    ('day', 'second'):86400,
    ('day', 'minute'):1440,
    ('day', 'hour'):24,
    ('day', 'day'):1,
    ('day', 'week'):1/7,
    ('day', 'month'):1/30.416,
    ('day', 'year'):1/365,
    ('week', 'millisecond'):6.048e+8,
    ('week', 'second'):604800,
    ('week', 'minute'):10080,
    ('week', 'hour'):168,
    ('week', 'day'):7,
    ('week', 'week'):1,
    ('week', 'month'):1/4.345,
    ('week', 'year'):1/52.143,
    ('month', 'millisecond'):2.628e+9,
    ('month', 'second'):2.628e+6,
    ('month', 'minute'):43800,
    ('month', 'hour'):730,
    ('month', 'day'):30.417,
    ('month', 'week'):4.345,
    ('month', 'month'):1,
    ('month', 'year'):1/12,
    ('year', 'millisecond'):3.154e+10,
    ('year', 'second'):3.154e+7,
    ('year', 'minute'):525600,
    ('year', 'hour'):8760,
    ('year', 'day'):365,
    ('year', 'week'):52.1429,
    ('year', 'month'):12,
    ('year', 'year'):1,
    ('cubic_metr', 'cubic_metr'):1,
    ('cubic_metr', 'liter'):1000,
    ('cubic_metr', 'milliliter'):1e+6,
    ('cubic_metr', 'cubic_foot'):35.315,
    ('cubic_metr', 'cubic_inch'):61023.7,
    ('liter', 'cubic_metr'):1/1000,
    ('liter', 'liter'):1,
    ('liter', 'milliliter'):1000,
    ('liter', 'cubic_foot'):1/28.317,
    ('liter', 'cubic_inch'):61.024,
    ('milliliter', 'cubic_metr'):1e-6,
    ('milliliter', 'liter'):1/1000,
    ('milliliter', 'milliliter'):1,
    ('milliliter', 'cubic_foot'):1/28320,
    ('milliliter', 'cubic_inch'):1/16.387,
    ('cubic_foot', 'cubic_metr'):1/35.315,
    ('cubic_foot', 'liter'):28.317,
    ('cubic_foot', 'milliliter'):28320,
    ('cubic_foot', 'cubic_foot'):1,
    ('cubic_foot', 'cubic_inch'):1728,
    ('cubic_inch', 'cubic_metr'):1/61020,
    ('cubic_inch', 'liter'):1/61.24,
    ('cubic_inch', 'milliliter'):16.3871,
    ('cubic_inch', 'cubic_foot'):1/1728,
    ('cubic_inch', 'cubic_inch'):1,
    ('ton', 'ton'):1,
    ('ton', 'kilogram'):1000,
    ('ton', 'gram'):1e+6,
    ('ton', 'milligram'):1e+9,
    ('ton', 'microgram'):1e+12,
    ('ton', 'pound'):2204.62,
    ('kilogram', 'ton'):0.001,
    ('kilogram', 'kilogram'):1,
    ('kilogram', 'gram'):1000,
    ('kilogram', 'milligram'):1e+6,
    ('kilogram', 'microgram'):1e+9,
    ('kilogram', 'pound'):2.20462,
    ('gram', 'ton'):1e-6,
    ('gram', 'kilogram'):0.001,
    ('gram', 'gram'):1,
    ('gram', 'milligram'):1000,
    ('gram', 'microgram'):1e+6,
    ('gram', 'pound'):0.00220462,
    ('milligram', 'ton'):1e-9,
    ('milligram', 'kilogram'):1e-6,
    ('milligram', 'gram'):0.001,
    ('milligram', 'milligram'):1,
    ('milligram', 'microgram'):1000,
    ('milligram', 'pound'):2.2046e-6,
    ('microgram', 'ton'):1e-12,
    ('microgram', 'kilogram'):1e-9,
    ('microgram', 'gram'):1e-6,
    ('microgram', 'milligram'):0.001,
    ('microgram', 'microgram'):1,
    ('microgram', 'pound'):2.2046e-9,
    ('pound', 'ton'):0.00045359,
    ('pound', 'kilogram'):0.453592,
    ('pound', 'gram'):453.592,
    ('pound', 'milligram'):453592,
    ('pound', 'microgram'):4.536e+8,
    ('pound', 'pound'):1,
    ('square_metr', 'square_metr'):1,
    ('square_metr', 'square_kilometer'):1e-6,
    ('square_metr', 'square_mile'):3.861e-7,
    ('square_metr', 'square_yard'):1.19599,
    ('square_metr', 'square_inch'):1550,
    ('square_metr', 'hectare'):1e-4,
    ('square_metr', 'acre'):0.000247105,
    ('square_kilometer', 'square_metr'):1e+6,
    ('square_kilometer', 'square_kilometer'):1,
    ('square_kilometer', 'square_mile'):0.386102,
    ('square_kilometer', 'square_yard'):1.196e+6,
    ('square_kilometer', 'square_inch'):1.55e+9,
    ('square_kilometer', 'hectare'):100,
    ('square_kilometer', 'acre'):247.105,
    ('square_mile', 'square_metr'):2.59e+6,
    ('square_mile', 'square_kilometer'):2.58999,
    ('square_mile', 'square_mile'):1,
    ('square_mile', 'square_yard'):3.098e+6,
    ('square_mile', 'square_inch'):4.014e+9,
    ('square_mile', 'hectare'):258.999,
    ('square_mile', 'acre'):640,
    ('square_yard', 'square_metr'):0.836127,
    ('square_yard', 'square_kilometer'):8.3613e-7,
    ('square_yard', 'square_mile'):3.2283e-7,
    ('square_yard', 'square_yard'):1,
    ('square_yard', 'square_inch'):1296,
    ('square_yard', 'hectare'):8.3613e-5,
    ('square_yard', 'acre'):0.000206612,
    ('square_inch', 'square_metr'):0.00064516,
    ('square_inch', 'square_kilometer'):6.4516e-10,
    ('square_inch', 'square_mile'):2.491e-10,
    ('square_inch', 'square_yard'):0.000771605,
    ('square_inch', 'square_inch'):1,
    ('square_inch', 'hectare'):6.4516e-8,
    ('square_inch', 'acre'):1.5942e-7,
    ('hectare', 'square_metr'):10000,
    ('hectare', 'square_kilometer'):0.01,
    ('hectare', 'square_mile'):0.00386102,
    ('hectare', 'square_yard'):11959.9,
    ('hectare', 'square_inch'):1.55e+7,
    ('hectare', 'hectare'):1,
    ('hectare', 'acre'):2.47105,
    ('acre', 'square_metr'):4046.86,
    ('acre', 'square_kilometer'):0.00404686,
    ('acre', 'square_mile'):0.0015625,
    ('acre', 'square_yard'):4840,
    ('acre', 'square_inch'):6.273e+6,
    ('acre', 'hectare'):0.404686,
    ('acre', 'acre'):1,
    ('mile_per_hour', 'mile_per_hour'):1,
    ('mile_per_hour', 'foot_per_second'):1.46667,
    ('mile_per_hour', 'metr_per_second'):0.44704,
    ('mile_per_hour', 'kilometr_per_hour'):1.60934,
    ('foot_per_second', 'mile_per_hour'):0.681818,
    ('foot_per_second', 'foot_per_second'):1,
    ('foot_per_second', 'metr_per_second'):0.3048,
    ('foot_per_second', 'kilometr_per_hour'):1.09728,
    ('metr_per_second', 'mile_per_hour'):2.23694,
    ('metr_per_second', 'foot_per_second'):3.28084,
    ('metr_per_second', 'metr_per_second'):1,
    ('metr_per_second', 'kilometr_per_hour'):3.6,
    ('kilometr_per_hour', 'mile_per_hour'):0.621371,
    ('kilometr_per_hour', 'foot_per_second'):0.911344,
    ('kilometr_per_hour', 'metr_per_second'):0.277778,
    ('kilometr_per_hour', 'kilometr_per_hour'):1,
}

def convert(request):
    form = ConverterForm()
    form2 = FormChoice()
    form3 = InputAndResult()
    context = {
            "form": form,
            "form2": form2,
            "form3": form3,
        }
    if request.GET:
        choiceVal = request.GET['choiceVal']
        input_unit = request.GET['input_unit']
        input_value = request.GET['input_value']
        output_unit = request.GET['output_unit']
        output_value = 0
        data = {
            "input_unit": input_unit,
            "input_value": input_value,
            "output_unit": output_unit,
            "output_value": round(output_value, 3)
        }
        match choiceVal:
            case "time":
                form = TimeForm(initial=data)
            case "pressure":
                form = PressureForm(initial=data)
            case "volume":
                form = VolumeForm(initial=data)
            case "mass":
                form = MassForm(initial=data)
            case "square":
                form = SquareForm(initial=data)
            case "speed":
                form = SpeedForm(initial=data)
            case "energy":
                form = EnergyForm(initial=data)
            case "frequency":
                form = FrequencyForm(initial=data)
            case "length":
                form = LengthForm(initial=data)
            case _:
                form = ConverterForm(initial=data)
        if (input_value != '' and input_unit != 'choice' and output_unit != 'choice'):
            output_value = float(input_value)*MEASURE_RATIO[(input_unit, output_unit)]
        form3 = InputAndResult(initial={"input_value": input_value, "output_value": output_value})
        form2 = FormChoice(initial={"choiceVal": choiceVal})
        context = {
            "form": form,
            "form2": form2,
            "form3": form3,
        }
        return render(
            request, "converter/index.html", context=context)
    return render(
        request, "converter/index.html", context=context)